//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLABORADOR()
        {
            this.COLABORADOR_ACCION_PERSONAL = new HashSet<COLABORADOR_ACCION_PERSONAL>();
            this.CONCEPTO_COLABORADOR = new HashSet<CONCEPTO_COLABORADOR>();
            this.CONTROL_ASISTENCIA = new HashSet<CONTROL_ASISTENCIA>();
        }
    
        public int IdColaborador { get; set; }
        public string Nombre { get; set; }
        public string Genero { get; set; }
        public bool Activo { get; set; }
        public string Estado { get; set; }
        public string Direccion { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Identificacion { get; set; }
        public string Nacionalidad { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public System.DateTime FechaSalida { get; set; }
        public int IdNomina { get; set; }
        public string EstadoCivil { get; set; }
        public decimal SaldoVacaciones { get; set; }
        public System.DateTime UltCalculoVacaciones { get; set; }
        public int IdPuesto { get; set; }
        public string FormaPago { get; set; }
        public string CuentaBancaria { get; set; }
        public string Banco { get; set; }
        public string CorreoElectronico { get; set; }
        public string ContactoEmergencia { get; set; }
        public string TelefonoContacto { get; set; }
        public decimal SalarioReferencia { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual NOMINA NOMINA { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADOR_ACCION_PERSONAL> COLABORADOR_ACCION_PERSONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONCEPTO_COLABORADOR> CONCEPTO_COLABORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL_ASISTENCIA> CONTROL_ASISTENCIA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
    }
}
