//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADOR_ACCION_PERSONAL
    {
        public int Id_Accion { get; set; }
        public int IdColaborador { get; set; }
        public int IdTipoAccionPers { get; set; }
        public System.DateTime FechaAccion { get; set; }
        public System.DateTime FechaRige { get; set; }
        public System.DateTime FechaVence { get; set; }
        public decimal DiasAccion { get; set; }
        public decimal SalarioReferencia { get; set; }
        public string EstadoEmpleado { get; set; }
        public string EstadoAccion { get; set; }
        public string Aprovador { get; set; }
        public System.DateTime FechaAprobacion { get; set; }
        public string Aplicador { get; set; }
        public System.DateTime FechaAplicacion { get; set; }
        public string Anulador { get; set; }
        public System.DateTime FechaAnulacion { get; set; }
        public string Notas { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual COLABORADOR COLABORADOR { get; set; }
        public virtual TIPO_ACCION_PERS TIPO_ACCION_PERS { get; set; }
    }
}
