//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCEPTO_FORMULA
    {
        public int IdConcepto { get; set; }
        public int IdFormula { get; set; }
        public decimal ValorInicial { get; set; }
        public decimal ValorFinal { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Monto { get; set; }
        public string Formula { get; set; }
        public bool UsaCantidad { get; set; }
        public bool UsaMonto { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModicacion { get; set; }
        public string FechaModificacion { get; set; }
    
        public virtual CONCEPTO CONCEPTO { get; set; }
    }
}
