//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCEPTO_COLABORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONCEPTO_COLABORADOR()
        {
            this.PLANILLA_DETALLE = new HashSet<PLANILLA_DETALLE>();
        }
    
        public int IdConcepto { get; set; }
        public int IdColaborador { get; set; }
        public int IdNomina { get; set; }
        public string SaldoAcomulado { get; set; }
        public System.DateTime FechaUltAplicacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual COLABORADOR COLABORADOR { get; set; }
        public virtual CONCEPTO CONCEPTO { get; set; }
        public virtual NOMINA NOMINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA_DETALLE> PLANILLA_DETALLE { get; set; }
    }
}
