//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONCEPTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONCEPTO()
        {
            this.CONCEPTO_COLABORADOR = new HashSet<CONCEPTO_COLABORADOR>();
            this.CONCEPTO_FORMULA = new HashSet<CONCEPTO_FORMULA>();
        }
    
        public int IdConcepto { get; set; }
        public string Alias { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string Unidad { get; set; }
        public bool Salarial { get; set; }
        public bool Fijo { get; set; }
        public bool Liquidable { get; set; }
        public bool CantEditable { get; set; }
        public bool MontoEditable { get; set; }
        public string Periodicidad { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONCEPTO_COLABORADOR> CONCEPTO_COLABORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONCEPTO_FORMULA> CONCEPTO_FORMULA { get; set; }
    }
}
