//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    
    public partial class f_opcionesUsuariosPerfil_Result2
    {
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
    }
}
