//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANILLA()
        {
            this.PLANILLA_DETALLE = new HashSet<PLANILLA_DETALLE>();
        }
    
        public string Consecutivo { get; set; }
        public int IdNomina { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public System.DateTime FechaFinal { get; set; }
        public string Periodo { get; set; }
        public int Anio { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal BeneficioTotal { get; set; }
        public decimal DeduccionTotal { get; set; }
        public decimal ProyeccionTotal { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual NOMINA NOMINA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANILLA_DETALLE> PLANILLA_DETALLE { get; set; }
    }
}
