//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA_COLABORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANILLA_COLABORADOR()
        {
            this.DOCUMENTO_CXP = new HashSet<DOCUMENTO_CXP>();
        }
    
        public string Liquidacion { get; set; }
        public string Consecutivo { get; set; }
        public int IdNomina { get; set; }
        public int IdColaborador { get; set; }
        public string Estado { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal BeneficioTotal { get; set; }
        public decimal DeduccionTotal { get; set; }
        public decimal ProyeccionTotal { get; set; }
        public System.DateTime UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCUMENTO_CXP> DOCUMENTO_CXP { get; set; }
        public virtual PLANILLA_DETALLE PLANILLA_DETALLE { get; set; }
    }
}
