//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SICOAdmin1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_ACCION_PERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_ACCION_PERS()
        {
            this.COLABORADOR_ACCION_PERSONAL = new HashSet<COLABORADOR_ACCION_PERSONAL>();
        }
    
        public int IdTipoAccionPers { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public string EstadoEmpleado { get; set; }
        public bool RestableceEstado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLABORADOR_ACCION_PERSONAL> COLABORADOR_ACCION_PERSONAL { get; set; }
    }
}
